spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

springdoc:
  swagger-ui:
    urls:
      - name: "develop"
        url: "http://localhost:8080/v3/api-docs"
